### ISSUE TITLE
Code blocks in comments don't wrap

### ISSUE THREAD

**Issue by MatthiasPortzel** [OurJSEditor/OurJSEditor#180]
Found this a while ago, but forgot about it. Should be something like 

```css
code pre {
    overflow: auto
}
```

https://ourjseditor.com/program/omEKO0#comment-zTtDRkMWog
